FROM ubuntu:lucid

RUN echo 'deb http://neuro.debian.net/debian lucid main' > /etc/apt/sources.list.d/neurodebian.sources.list
RUN echo 'deb http://neuro.debian.net/debian data main' >> /etc/apt/sources.list.d/neurodebian.sources.list
RUN echo '#deb-src http://neuro.debian.net/debian-devel lucid main' >> /etc/apt/sources.list.d/neurodebian.sources.list
