FROM ubuntu:raring

RUN echo 'deb http://neuro.debian.net/debian raring main' > /etc/apt/sources.list.d/neurodebian.sources.list
RUN echo 'deb http://neuro.debian.net/debian data main' >> /etc/apt/sources.list.d/neurodebian.sources.list
RUN echo '#deb-src http://neuro.debian.net/debian-devel raring main' >> /etc/apt/sources.list.d/neurodebian.sources.list
