FROM ubuntu:saucy

RUN echo 'deb http://neuro.debian.net/debian saucy main' > /etc/apt/sources.list.d/neurodebian.sources.list
RUN echo 'deb http://neuro.debian.net/debian data main' >> /etc/apt/sources.list.d/neurodebian.sources.list
RUN echo '#deb-src http://neuro.debian.net/debian-devel saucy main' >> /etc/apt/sources.list.d/neurodebian.sources.list
